version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_TEST_HOST: db_test

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: outfit7
    volumes:
      - db_data:/var/lib/postgresql/data

  db_test:
    build:
      context: .
      dockerfile: Dockerfile.postgres_test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: outfit7_test
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_data:
  db_test_data:
